name: Hello World!

on:
  [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Now it is
        run: |
          echo date
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Directory content
        run: |
          echo ls