name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_DEPLOY: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run eslint

      - name: Run unit tests
        run: npm run test
      
      - name: Run build
        run: npm run build

      - name: Build Failure Notification
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          text: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      #- name: Install Playwright dependencies
       # run: npx playwright install --with-deps

      #- name: e2e tests
      #  run: npm run test:e2e

      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && env.SKIP_DEPLOY == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Notify success
        uses: stegzilla/discord-notify@v4
        if: success()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: A new version of Pokedex deployed!
          message: 'to https://full-stack-open-pokedex-jvcn.onrender.com/ by **${{ github.actor }}**'
          include_image: true
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: GitHub PR Notifier

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0' 
      - name: Bump version and push tag
        if: ${{ env.SKIP_DEPLOY == 'false' }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
